#!/usr/bin/env python3
"""Keep pstack identical to Cursor's upstream and build a Codex-ready copy.

upstream/  verbatim copy of cursor/plugins/pstack at the ref in UPSTREAM
overlay/   the only files this repository owns (harness map, patches, examples)
dist/      generated by "build"; skills are installed as symlinks into dist/skills
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
UPSTREAM_DIR = REPO / "upstream"
OVERLAY_DIR = REPO / "overlay"
DIST_DIR = REPO / "dist"
LOCK_FILE = REPO / "UPSTREAM"
CODEX_HOME = Path(os.environ.get("CODEX_HOME", Path.home() / ".codex"))
DEFAULT_MODELS_FILE = CODEX_HOME / "pstack-models.md"
DEFAULT_CATALOG = CODEX_HOME / "models_cache.json"
EFFORTS = ["low", "medium", "high", "xhigh", "max", "ultra"]
ALIASES = {"inherit-parent", "auto"}
FENCE = chr(96) * 3
POINTER = (
    "> Codex: before following this skill, read {dist}/HARNESS.md if you have not read it "
    "in this session. It maps Cursor tools, paths, and model names to this environment.\n"
)


def run(cmd: list[str], cwd: Path | None = None) -> str:
    result = subprocess.run(cmd, cwd=cwd, check=True, text=True, capture_output=True)
    return result.stdout.strip()


def read_lock() -> dict[str, str]:
    lock = {}
    for line in LOCK_FILE.read_text().splitlines():
        if "=" in line and not line.startswith("#"):
            key, value = line.split("=", 1)
            lock[key.strip()] = value.strip()
    return lock


def write_lock(lock: dict[str, str]) -> None:
    LOCK_FILE.write_text("".join(f"{key}={value}\n" for key, value in lock.items()))


def cmd_sync(args: argparse.Namespace) -> None:
    lock = read_lock()
    old_ref = lock.get("ref", "")
    with tempfile.TemporaryDirectory(prefix="pstack-sync-") as tmp:
        clone = Path(tmp) / "plugins"
        run(["git", "clone", "-q", "--filter=blob:none", "--no-checkout", "--sparse", lock["repo"], str(clone)])
        run(["git", "sparse-checkout", "set", lock["path"]], cwd=clone)
        ref = args.ref or run(["git", "log", "-1", "--format=%H", "origin/HEAD", "--", lock["path"]], cwd=clone)
        ref = run(["git", "rev-parse", ref + "^{commit}"], cwd=clone)
        run(["git", "checkout", "-q", ref], cwd=clone)
        if old_ref and old_ref != ref:
            log = run(["git", "log", "--format=%h %cs %s", f"{old_ref}..{ref}", "--", lock["path"]], cwd=clone)
            print(f"upstream changes {old_ref[:7]}..{ref[:7]}:\n{log or '(none under ' + lock['path'] + ')'}")
        if UPSTREAM_DIR.exists():
            shutil.rmtree(UPSTREAM_DIR)
        shutil.copytree(clone / lock["path"], UPSTREAM_DIR)
    lock["ref"] = ref
    write_lock(lock)
    print(f"upstream/ now matches {lock['repo']} {lock['path']} @ {ref}")
    print("Next: review 'git diff --stat upstream', then run build and check-models.")


def split_frontmatter(text: str) -> tuple[list[str], str]:
    if not text.startswith("---\n"):
        raise ValueError("missing frontmatter")
    end = text.index("\n---\n", 4)
    return text[4:end].splitlines(), text[end + 5 :]


def adapt_skill(skill_dir: Path, dist: Path) -> bool:
    """Normalize the name, map disable-model-invocation, add the harness pointer."""
    skill_md = skill_dir / "SKILL.md"
    front, body = split_frontmatter(skill_md.read_text())
    explicit_only = any(line.strip() == "disable-model-invocation: true" for line in front)
    front = [f"name: {skill_dir.name}" if line.startswith("name:") else line for line in front]
    pointer = "" if skill_dir.name.startswith("principle-") else POINTER.format(dist=dist)
    skill_md.write_text("---\n" + "\n".join(front) + "\n---\n" + pointer + body)
    if explicit_only:
        meta = skill_dir / "agents" / "openai.yaml"
        if meta.exists():
            raise SystemExit(f"{meta} now exists upstream; merge its policy by hand")
        meta.parent.mkdir(exist_ok=True)
        meta.write_text("policy:\n  allow_implicit_invocation: false\n")
    return explicit_only


def cmd_build(args: argparse.Namespace) -> None:
    dist = Path(args.out).resolve()
    if dist.exists():
        shutil.rmtree(dist)
    dist.mkdir(parents=True)
    shutil.copytree(UPSTREAM_DIR / "skills", dist / "skills")
    shutil.copytree(UPSTREAM_DIR / "agents", dist / "agents")

    excluded = [line.strip() for line in (OVERLAY_DIR / "exclude").read_text().splitlines()
                if line.strip() and not line.startswith("#")]
    for name in excluded:
        if (dist / "skills" / name).exists():
            shutil.rmtree(dist / "skills" / name)
        else:
            print(f"note: excluded skill {name} no longer exists upstream; drop it from overlay/exclude")

    for patch in sorted((OVERLAY_DIR / "patches").glob("*.patch")):
        base = ["patch", "-p1", "--batch", "--forward", "--no-backup-if-mismatch", "-d", str(dist), "-i", str(patch)]
        check = subprocess.run(base + ["--dry-run"], text=True, capture_output=True)
        if check.returncode != 0:
            raise SystemExit(f"{patch.name} no longer applies to upstream; update it.\n{check.stdout}{check.stderr}")
        run(base)
        print(f"applied {patch.name}")

    explicit = 0
    skills = sorted(p for p in (dist / "skills").iterdir() if (p / "SKILL.md").exists())
    for skill_dir in skills:
        explicit += adapt_skill(skill_dir, dist)

    harness = (OVERLAY_DIR / "HARNESS.md").read_text()
    harness = harness.replace("{{PSTACK_DIST}}", str(dist)).replace("{{PSTACK_REPO}}", str(REPO))
    (dist / "HARNESS.md").write_text(harness)

    overlay_rev = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=REPO, text=True, capture_output=True)
    info = {
        "upstream": read_lock(),
        "overlay_commit": overlay_rev.stdout.strip() or None,
        "built_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "skills": len(skills),
        "explicit_only": explicit,
        "excluded": excluded,
    }
    (dist / "BUILD-INFO.json").write_text(json.dumps(info, indent=2) + "\n")
    print(f"built {len(skills)} skills into {dist} ({explicit} explicit-only)")


def load_catalog(path: Path) -> dict[str, list[str]]:
    data = json.loads(path.read_text())
    catalog = {}
    for model in data.get("models", []):
        raw_levels = model.get("supported_reasoning_levels") or []
        if not isinstance(raw_levels, list):
            raise ValueError("supported_reasoning_levels must be an array")
        levels = [lvl.get("effort") if isinstance(lvl, dict) else lvl for lvl in raw_levels]
        if any(not isinstance(lvl, str) for lvl in levels):
            raise ValueError("reasoning levels must be strings or objects with string efforts")
        catalog[model["slug"]] = [lvl for lvl in levels if lvl in EFFORTS]
    return catalog


def split_effort(value: str) -> tuple[str, str | None]:
    tokens = value.split("-")
    if tokens[-1] == "fast":
        tokens = tokens[:-1]
    if len(tokens) > 1 and tokens[-1] in EFFORTS:
        return "-".join(tokens[:-1]), tokens[-1]
    return "-".join(tokens), None


def match_slug(name: str, catalog: dict[str, list[str]]) -> str | None:
    if name in catalog:
        return name

    def norm(slug: str) -> str:
        return slug.rsplit("/", 1)[-1].replace(".", "-").lower()

    candidates = [slug for slug in catalog if norm(slug) == norm(name)]
    rank = lambda slug: (0 if slug.startswith("anthropic/") else 1 if "/" not in slug else 2, slug)
    return min(candidates, key=rank) if candidates else None


def clamp(effort: str | None, levels: list[str]) -> str | None:
    if effort is None or not levels or effort in levels:
        return effort
    lower = [lvl for lvl in levels if EFFORTS.index(lvl) <= EFFORTS.index(effort)]
    return max(lower or [min(levels, key=EFFORTS.index)], key=EFFORTS.index)


def resolve(value: str, catalog: dict[str, list[str]]) -> tuple[str, str]:
    if value in ALIASES:
        return "(parent model)", "ok"
    name, effort = split_effort(value)
    slug = match_slug(name, catalog)
    if slug is None:
        return f"{name} is not in the Codex catalog", "missing"
    final = clamp(effort, catalog[slug])
    note = "" if final == effort else f" (clamped from {effort})"
    return f"model={slug} reasoning_effort={final or '(parent)'}{note}", "ok"


def parse_roles(text: str) -> dict[str, list[str]]:
    roles = {}
    for line in text.splitlines():
        if line.startswith("#") or ":" not in line or line.startswith(("description:", "alwaysApply:")):
            continue
        label, values = line.split(":", 1)
        if label.strip() and values.strip():
            roles[label.strip()] = [v.strip() for v in values.split(",") if v.strip()]
    return roles


def upstream_roles() -> dict[str, list[str]]:
    text = (UPSTREAM_DIR / "skills" / "setup-pstack" / "SKILL.md").read_text()
    block = re.search(r"### 5\..*?" + FENCE + r"\n(.*?)" + FENCE, text, re.S)
    if not block:
        raise SystemExit("could not find the role template in upstream setup-pstack; review check-models")
    return parse_roles(block.group(1))


def cmd_check_models(args: argparse.Namespace) -> None:
    catalog = load_catalog(Path(args.catalog))
    defaults = upstream_roles()
    if args.defaults:
        roles, source = defaults, "upstream defaults"
    else:
        path = Path(args.file).expanduser()
        if not path.exists():
            raise SystemExit(f"{path} does not exist; run $setup-pstack or copy overlay/pstack-models.example.md")
        roles, source = parse_roles(path.read_text()), str(path)
    print(f"checking names and reasoning efforts in {source} against {args.catalog}")
    print("This does not verify collaboration transport or live provider availability; run check-runtime before delegation.")
    records = json.loads(Path(args.catalog).read_text()).get("models", [])
    disabled = {model["slug"] for model in records if model.get("multi_agent_version") == "disabled"}
    failures = 0
    for label, values in roles.items():
        known = "" if label in defaults else "  [not an upstream role line]"
        failures += bool(known)
        for value in values:
            detail, status = resolve(value, catalog)
            slug = match_slug(split_effort(value)[0], catalog)
            if slug in disabled:
                detail, status = f"{slug} is disabled for collaboration in the catalog", "disabled"
            failures += status != "ok"
            print(f"{'OK ' if status == 'ok' else 'ERR'} {label}: {value} -> {detail}{known}")
    for label in defaults:
        if label not in roles:
            print(f"--  {label}: no line, the skill default applies")
    if failures:
        raise SystemExit(f"{failures} problem(s) found")


def cmd_check_runtime(args: argparse.Namespace) -> None:
    from pstack_runtime import catalog_records, configured_catalog, diagnose, read_object, select_profile

    try:
        codex_path = Path(args.codex_config).expanduser()
        opencodex_path = Path(args.opencodex_config).expanduser()
        codex_config = select_profile(read_object(codex_path, toml=True), args.profile)
        opencodex_config = read_object(opencodex_path)
        catalog_path = configured_catalog(codex_config, codex_path.parent, args.catalog)
        records = catalog_records(catalog_path)
        catalog = load_catalog(catalog_path)
        parent = match_slug(split_effort(args.parent_model)[0], catalog)
        if parent is None:
            raise ValueError("parent model is not in the selected catalog")
        known_roles = upstream_roles()
        roles = known_roles if args.defaults else parse_roles(Path(args.file).expanduser().read_text())
        if not roles:
            raise ValueError("no model roles found")
        if args.role:
            if any(role not in roles for role in args.role):
                raise ValueError("selected role is not in the model settings")
            roles = {role: roles[role] for role in args.role}
        children = {}
        for role, values in roles.items():
            if role not in known_roles:
                raise ValueError(f"unknown pstack role: {role}")
            for value in values:
                slug = parent if value in ALIASES else match_slug(split_effort(value)[0], catalog)
                if slug is None:
                    raise ValueError(f"model for role {role} is not in the selected catalog")
                children.setdefault(slug, []).append(role)
        report = diagnose(parent, children, records, codex_config, opencodex_config, args.session_surface)
        report["paths"] = {"catalog": str(catalog_path), "codex_config": str(codex_path), "opencodex_config": str(opencodex_path)}
        for path in (codex_path, opencodex_path):
            if not path.exists():
                report["issues"].append({"level": "warning", "code": "config_missing", "message": f"Configuration file is missing: {path}"})
                if report["status"] == "CONFIGURATION_OK":
                    report["status"] = "INCONCLUSIVE"
    except (OSError, ValueError) as error:
        report = {"status": "BLOCKED", "live_delegation_verified": False, "issues": [{"level": "error", "code": "invalid_input", "message": str(error)}]}
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(f"runtime: {report['status']} (live delegation is not verified)")
        if "parent" in report:
            print(f"session surface: {report['session_surface']}; parent: {report['parent']['model']} ({report['parent']['route']})")
            print(f"catalog: {report['paths']['catalog']}")
            for child in report["children"]:
                print(f"child: {child['model']} ({child['route']}, catalog surface={child['catalog_surface']})")
        for item in report["issues"]:
            print(f"{item['level'].upper()} {item['code']}: {item['message']}")
    if report["status"] != "CONFIGURATION_OK":
        raise SystemExit(1 if report["status"] == "BLOCKED" else 2)


def cmd_install(args: argparse.Namespace) -> None:
    target = Path(args.target).expanduser().resolve()
    target.mkdir(parents=True, exist_ok=True)
    skills = sorted(p for p in (DIST_DIR / "skills").iterdir() if (p / "SKILL.md").exists())
    if not skills:
        raise SystemExit("dist/ is empty; run build first")
    clashes = [target / s.name for s in skills if (target / s.name).exists() and not (target / s.name).is_symlink()]
    if clashes:
        raise SystemExit("refusing to replace existing directories:\n" + "\n".join(map(str, clashes)))
    for skill in skills:
        link = target / skill.name
        if link.is_symlink():
            link.unlink()
        link.symlink_to(skill)
    stale = [link for link in target.iterdir()
             if link.is_symlink() and str(os.readlink(link)).startswith(str(DIST_DIR)) and not link.exists()]
    for link in stale:
        link.unlink()
    print(f"linked {len(skills)} skills into {target}" + (f", removed {len(stale)} stale links" if stale else ""))


def cmd_uninstall(args: argparse.Namespace) -> None:
    target = Path(args.target).expanduser().resolve()
    removed = 0
    for link in target.iterdir():
        if link.is_symlink() and str(os.readlink(link)).startswith(str(DIST_DIR)):
            link.unlink()
            removed += 1
    print(f"removed {removed} pstack links from {target}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    sync = sub.add_parser("sync", help="replace upstream/ with cursor/plugins/pstack at a ref (default: latest)")
    sync.add_argument("--ref")
    sync.set_defaults(func=cmd_sync)
    build = sub.add_parser("build", help="generate dist/ from upstream/ and overlay/")
    build.add_argument("--out", default=str(DIST_DIR))
    build.set_defaults(func=cmd_build)
    check = sub.add_parser("check-models", help="resolve pstack model settings against the Codex catalog")
    check.add_argument("--file", default=str(DEFAULT_MODELS_FILE))
    check.add_argument("--catalog", default=str(DEFAULT_CATALOG))
    check.add_argument("--defaults", action="store_true", help="check upstream's default role table instead")
    check.set_defaults(func=cmd_check_models)
    runtime = sub.add_parser("check-runtime", help="read-only delegation preflight; existing-session uncertainty returns exit 2")
    runtime.add_argument("--parent-model", required=True)
    runtime.add_argument("--session-surface", choices=("unknown", "v1", "v2"), default="unknown", help="observed live session surface, never inferred from disk configuration")
    runtime.add_argument("--file", default=str(DEFAULT_MODELS_FILE))
    runtime.add_argument("--role", action="append", help="check only this role; repeat to select more roles")
    runtime.add_argument("--catalog", help="catalog override; otherwise honor Codex model_catalog_json")
    runtime.add_argument("--codex-config", default=str(CODEX_HOME / "config.toml"))
    runtime.add_argument("--profile", help="Codex profile used by the client, if any")
    runtime.add_argument("--opencodex-config", default=str(Path(os.environ.get("OPENCODEX_HOME", Path.home() / ".opencodex")) / "config.json"))
    runtime.add_argument("--defaults", action="store_true")
    runtime.add_argument("--json", action="store_true")
    runtime.set_defaults(func=cmd_check_runtime)
    install = sub.add_parser("install", help="symlink dist/skills/* into a skills folder")
    install.add_argument("--target", required=True)
    install.set_defaults(func=cmd_install)
    uninstall = sub.add_parser("uninstall", help="remove symlinks that point into dist/")
    uninstall.add_argument("--target", required=True)
    uninstall.set_defaults(func=cmd_uninstall)
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    sys.exit(main())
